const FETCH_DRAFTS_REQUEST = 'draftsforfriends/FETCH_DRAFTS_REQUEST';
const FETCH_DRAFTS_SUCCESS = 'draftsforfriends/FETCH_DRAFTS_SUCCESS';
const FETCH_DRAFTS_FAILURE = 'draftsforfriends/FETCH_DRAFTS_FAILURE';

const FETCH_SHARED_DRAFTS_REQUEST = 'draftsforfriends/FETCH_SHARED_DRAFTS_REQUEST';
const FETCH_SHARED_DRAFTS_SUCCESS = 'draftsforfriends/FETCH_SHARED_DRAFTS_SUCCESS';
const FETCH_SHARED_DRAFTS_FAILURE = 'draftsforfriends/FETCH_SHARED_DRAFTS_FAILURE';

const SHARE_DRAFT_REQUEST = 'draftsforfriends/SHARE_DRAFT_REQUEST';
const SHARE_DRAFT_SUCCESS = 'draftsforfriends/SHARE_DRAFT_SUCCESS';
const SHARE_DRAFT_FAILURE = 'draftsforfriends/SHARE_DRAFT_FAILURE';

const UNSHARE_DRAFT_REQUEST = 'draftsforfriends/UNSHARE_DRAFT_REQUEST';
const UNSHARE_DRAFT_SUCCESS = 'draftsforfriends/UNSHARE_DRAFT_SUCCESS';
const UNSHARE_DRAFT_FAILURE = 'draftsforfriends/UNSHARE_DRAFT_FAILURE';

const EXTEND_SHARE_REQUEST = 'draftsforfriends/EXTEND_SHARE_REQUEST';
const EXTEND_SHARE_SUCCESS = 'draftsforfriends/EXTEND_SHARE_SUCCESS';
const EXTEND_SHARE_FAILURE = 'draftsforfriends/EXTEND_SHARE_FAILURE';

export {
	FETCH_DRAFTS_REQUEST,
	FETCH_DRAFTS_SUCCESS,
	FETCH_DRAFTS_FAILURE,
	FETCH_SHARED_DRAFTS_REQUEST,
	FETCH_SHARED_DRAFTS_SUCCESS,
	FETCH_SHARED_DRAFTS_FAILURE,
	SHARE_DRAFT_REQUEST,
	SHARE_DRAFT_SUCCESS,
	SHARE_DRAFT_FAILURE,
	UNSHARE_DRAFT_REQUEST,
	UNSHARE_DRAFT_SUCCESS,
	UNSHARE_DRAFT_FAILURE,
	EXTEND_SHARE_REQUEST,
	EXTEND_SHARE_SUCCESS,
	EXTEND_SHARE_FAILURE,
};
